// <auto-generated />
namespace adminoperation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Qtyadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Qtyadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202304040539426_Qty added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
